apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-file-transfer-deployment-test
  namespace: ms-file-transfer-test-ns
  labels:
    app: ms-file-transfer-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-file-transfer-app-test
  template:
    metadata:
      labels:
        app: ms-file-transfer-app-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: ms-file-transfer-api-test
          image: 019146316808.dkr.ecr.us-west-2.amazonaws.com/ms-file-transfer-api:8c4935d1d2e6b0ba76e217f259ab12b33b4c9a5e
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
