name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Pull Request Checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # - name: Run linter
      #   run: npm run lint

      - name: Run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: Pull Request Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
